# Generated by Django 2.2.1 on 2019-06-03 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 6, 3, 11, 24, 48, 761895, tzinfo=utc), verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 6, 3, 11, 24, 56, 10623, tzinfo=utc), verbose_name='Creation date'),
            preserve_default=False,
        ),
    ]
