# Generated by Django 2.2.1 on 2019-06-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190603_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expirationfilter',
            options={'ordering': ['id'], 'verbose_name': 'ExpFilter', 'verbose_name_plural': 'ExpFilters'},
        ),
    ]
