# Generated by Django 2.2.1 on 2019-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='second_email',
            field=models.EmailField(max_length=254, verbose_name='Confirm email'),
        ),
    ]
